[[themes]]
name = "matugen"
[themes.palette]
foreground = "#f1dfdc"
black = "#000000"
red = "#ffd2cc"
green = "#f5d9a0"
yellow = "#fed2cb"
blue = "#ffd2cb"
magenta = "#a58e5b"
cyan = "#ae8882"
white = "#534341"
bright_black = "#c2adaa"
bright_red = "#ff5449"
bright_green = "#fbdfa6"
bright_yellow = "#ffdad4"
bright_blue = "#ffdad4"
bright_magenta = "#dec48c"
bright_cyan = "#e7bdb6"
bright_white = "#1a1110"
