# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="{{colors.on_surface.dark.hex}}"

# Title color for boxes
theme[title]="{{colors.primary.dark.hex}}"

# Highlight color for keyboard shortcuts
theme[hi_fg]="{{colors.secondary.dark.hex}}"

# Background color of selected item in processes box
theme[selected_bg]="{{colors.primary.dark.hex}}"

# Foreground color of selected item in processes box
theme[selected_fg]="{{colors.on_primary.dark.hex}}"

# Color of inactive/disabled text
theme[inactive_fg]="{{colors.on_surface_variant.dark.hex}}"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="{{colors.tertiary.dark.hex}}"

# Cpu box outline color
theme[cpu_box]="{{colors.outline.dark.hex}}"

# Memory/disks box outline color
theme[mem_box]="{{colors.outline.dark.hex}}"

# Net up/down box outline color
theme[net_box]="{{colors.outline.dark.hex}}"

# Processes box outline color
theme[proc_box]="{{colors.outline.dark.hex}}"

# Box divider line and small boxes line color
theme[div_line]="{{colors.outline_variant.dark.hex}}"

# Temperature graph colors
theme[temp_start]="{{colors.secondary.dark.hex}}"
theme[temp_mid]="{{colors.primary.dark.hex}}"
theme[temp_end]="{{colors.error.dark.hex}}"

# CPU graph colors
theme[cpu_start]="{{colors.secondary.dark.hex}}"
theme[cpu_mid]="{{colors.primary.dark.hex}}"
theme[cpu_end]="{{colors.error.dark.hex}}"

# Mem/Disk free meter
theme[free_start]="{{colors.secondary.dark.hex}}"
theme[free_mid]=""
theme[free_end]="{{colors.secondary_container.dark.hex}}"

# Mem/Disk cached meter
theme[cached_start]="{{colors.tertiary.dark.hex}}"
theme[cached_mid]=""
theme[cached_end]="{{colors.tertiary_container.dark.hex}}"

# Mem/Disk available meter
theme[available_start]="{{colors.primary.dark.hex}}"
theme[available_mid]=""
theme[available_end]="{{colors.primary_container.dark.hex}}"

# Mem/Disk used meter
theme[used_start]="{{colors.error.dark.hex}}"
theme[used_mid]=""
theme[used_end]="{{colors.error_container.dark.hex}}"

# Download graph colors
theme[download_start]="{{colors.secondary.dark.hex}}"
theme[download_mid]="{{colors.primary.dark.hex}}"
theme[download_end]="{{colors.tertiary.dark.hex}}"

# Upload graph colors
theme[upload_start]="{{colors.secondary.dark.hex}}"
theme[upload_mid]="{{colors.primary.dark.hex}}"
theme[upload_end]="{{colors.tertiary.dark.hex}}"
