[[themes]]
name = "matugen"
[themes.palette]
foreground = "{{colors.on_background.dark.hex}}"
black = "{{colors.shadow.dark.hex}}"
red = "{{colors.error.dark.hex}}"
green = "{{colors.tertiary.dark.hex}}"
yellow = "{{colors.secondary.dark.hex}}"
blue = "{{colors.primary.dark.hex}}"
magenta = "{{colors.tertiary_container.dark.hex}}"
cyan = "{{colors.secondary_container.dark.hex}}"
white = "{{colors.surface_variant.dark.hex}}"
bright_black = "{{colors.outline.dark.hex}}"
bright_red = "{{colors.error_container.dark.hex}}"
bright_green = "{{colors.tertiary_fixed.dark.hex}}"
bright_yellow = "{{colors.secondary_fixed.dark.hex}}"
bright_blue = "{{colors.primary_fixed.dark.hex}}"
bright_magenta = "{{colors.tertiary_fixed_dim.dark.hex}}"
bright_cyan = "{{colors.secondary_fixed_dim.dark.hex}}"
bright_white = "{{colors.surface.dark.hex}}"
